spring:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema/schema.sql
      data-locations: classpath:data/data1_dominios.sql, classpath:data/data2_estados.sql, classpath:data/data3_municipios.sql, classpath:data/data4_broker.sql, classpath:data/data5_company.sql, classpath:data/data6_stock_exchange.sql, classpath:data/data7_financial_asset.sql

  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:~/LULEKE_DATA;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS LULEKE_INVEST
    url: jdbc:h2:mem:LULEKE_DATA;DB_CLOSE_DELAY=-1;
    password: 
    username: sa
    
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 0

  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true